Added CSV products, products redux, sass :rice_ball:
EABModel/frontend pull request #11
Opened 2021-05-25 15:47 UTC by Fenho

2021-05-25 21:29 UTC, dasolari requested changes
Deje algunas solicitudes de cambios funcionales y no funcionales. Mejor cambiarlos ahora que no cambiarlos nunca. Later is never.

2021-05-25 21:29 UTC, dasolari commented on src/components/CatalogueMenu/ProductRegisterCSV.tsx
> +  }, [catalogue.addProductsToCatalogue, setShowSuccessMessage, props.resetCatalogueInteractor]);
Seguro que setShowSuccessMessage es una dependencia? Tengo entendido que al ser un hook useState puede causar problemas en dentro de un useEffect.

2021-05-25 21:29 UTC, dasolari commented on src/components/CatalogueMenu/ProductRegisterCSV.tsx
> +    console.log('---------------------------');
Borra cualquier console log que hayas usado para debbuggear. Generan código muerto y hacen el rendered más lento.

2021-05-25 21:29 UTC, dasolari commented on src/components/CatalogueMenu/ProductRegisterCSV.tsx
> +    // Called to reset the state
Lo mismo con estos comentarios, tampoco sirven.

2021-05-25 21:29 UTC, dasolari commented on src/services/catalogueServices.ts
> +      // Recieves an empty object to avoid changing shop state
Este comentario no explica esta función, sino que el del request de shop. Hay que borrarlo o cambiarlo para futura referencia.

2021-05-25 22:08 UTC, Fenho commented on src/components/CatalogueMenu/ProductRegisterCSV.tsx
> +  }, [catalogue.addProductsToCatalogue, setShowSuccessMessage, props.resetCatalogueInteractor]);
eso lo saque de tu codigo jaja

2021-05-25 22:08 UTC, Fenho commented on src/components/CatalogueMenu/ProductRegisterCSV.tsx
> +    console.log('---------------------------');
se me fue eso

2021-05-25 22:08 UTC, Fenho commented on src/components/CatalogueMenu/ProductRegisterCSV.tsx
> +    // Called to reset the state
same

2021-05-25 22:08 UTC, Fenho commented on src/services/catalogueServices.ts
> +      // Recieves an empty object to avoid changing shop state
Dale

2021-05-28 04:20 UTC, dasolari commented
Resolví los merge _conflicts_ del `yarn.lock`,si tira problemas, aca es!

2021-05-28 04:27 UTC, merged